import React, { useEffect, useState } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import { Layout } from '../components/Layout';
import { CodeBlock } from '../components/CodeBlock';
import { getNotebook, incrementViewCount, decompressToNotebook, compressSnippets } from '../services/storage';
import { Notebook } from '../types';
import { APP_CONFIG } from '../config';

export const NotebookView: React.FC = () => {
  const { slug, data } = useParams<{ slug?: string; data?: string }>();
  const navigate = useNavigate();
  const [notebook, setNotebook] = useState<Notebook | null>(null);
  const [loading, setLoading] = useState(true);
  const [canEdit, setCanEdit] = useState(false);
  const [copyStatus, setCopyStatus] = useState<'idle' | 'copied' | 'shared'>('idle');

  useEffect(() => {
    setLoading(true);
    
    if (data) {
        // Handle Shared URL
        const sharedNotebook = decompressToNotebook(data);
        if (sharedNotebook) {
            setNotebook(sharedNotebook);
            setCanEdit(false); // Shared views are always read-only
        }
        setLoading(false);
    } else if (slug) {
        // Handle Local Notebook
        const localData = getNotebook(slug);
        if (localData) {
            setNotebook(localData);
            incrementViewCount(slug);
            
            const localToken = localStorage.getItem(`${APP_CONFIG.TOKEN_KEY_PREFIX}${slug}`);
            if (localToken === localData.editToken) {
                setCanEdit(true);
            }
        }
        setLoading(false);
    }
  }, [slug, data]);

  const handlePrint = () => {
    window.print();
  };

  const handleDownload = () => {
    if (!notebook) return;
    
    // Generate simple markdown content
    let content = `# ${notebook.slug === 'shared' ? 'Shared Snippets' : notebook.slug}\n\n`;
    content += `> Generated by ${APP_CONFIG.APP_NAME}\n\n`;
    
    notebook.snippets.forEach(s => {
        content += `### ${s.title || 'Untitled'}\n`;
        content += "```" + (s.language === 'text' ? '' : s.language) + "\n";
        content += s.code + "\n";
        content += "```\n\n";
    });

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${notebook.slug === 'shared' ? 'snippets' : notebook.slug}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleShare = () => {
      if (!notebook) return;

      if (data) {
          // Already on a shared link
          navigator.clipboard.writeText(window.location.href);
          setCopyStatus('copied');
      } else {
          // Generate a compressed share link
          const compressed = compressSnippets(notebook.snippets);
          const shareUrl = `${window.location.origin}/#/s/${compressed}`;
          navigator.clipboard.writeText(shareUrl);
          setCopyStatus('shared');
      }

      setTimeout(() => setCopyStatus('idle'), 3000);
  };

  if (loading) {
    return <Layout><div className="pt-20 text-center text-pencil">Loading...</div></Layout>;
  }

  if (!notebook) {
    return (
      <Layout>
        <div className="pt-20 text-center">
          <h2 className="text-2xl font-bold mb-4">404: Notebook Not Found</h2>
          <p className="text-pencil mb-8">The requested content does not exist or is corrupted.</p>
          <Link to="/" className="underline hover:text-pencil">Create New</Link>
        </div>
      </Layout>
    );
  }

  return (
    <Layout>
      <div className="flex flex-col md:flex-row md:items-center justify-between mb-8 border-b border-line pb-6">
        <div>
           <h1 className="text-2xl font-bold break-all">
               {notebook.slug === 'shared' ? 'Shared Notebook' : `/${notebook.slug}`}
           </h1>
           <p className="text-xs text-pencil mt-1">
             {notebook.slug === 'shared' 
                ? 'Read-only view' 
                : `Created ${new Date(notebook.createdAt).toLocaleDateString()} • ${notebook.views} views`
             }
           </p>
        </div>
        
        <div className="mt-4 md:mt-0 flex flex-wrap gap-4 no-print items-center">
            <div className="flex gap-2">
                <button 
                    onClick={handleDownload}
                    className="text-xs border border-line px-3 py-1 hover:border-pencil transition-colors text-pencil hover:text-ink"
                    title="Download as Markdown"
                >
                    Save .md
                </button>
                 <button 
                    onClick={handlePrint}
                    className="text-xs border border-line px-3 py-1 hover:border-pencil transition-colors text-pencil hover:text-ink"
                    title="Print to PDF"
                >
                    PDF / Print
                </button>
            </div>
            <div className="h-6 w-px bg-line hidden md:block"></div>
             {canEdit && (
                <button 
                    onClick={() => navigate(`/n/${slug}/edit`)}
                    className="text-sm border border-ink bg-white px-4 py-1 hover:bg-gray-50 transition-colors shadow-sm"
                >
                    Edit
                </button>
            )}
             <button 
                onClick={handleShare}
                className={`text-sm font-medium transition-colors ${
                    copyStatus !== 'idle' ? 'text-green-600' : 'text-ink hover:text-pencil underline'
                }`}
            >
                {copyStatus === 'copied' && 'Link Copied!'}
                {copyStatus === 'shared' && 'Shareable Link Copied!'}
                {copyStatus === 'idle' && (notebook.slug === 'shared' ? 'Copy Link' : 'Share URL')}
            </button>
        </div>
      </div>

      <div className="space-y-12">
        {notebook.snippets.length === 0 ? (
             <div className="text-center py-12 text-pencil border border-dashed border-line">
                Empty notebook.
             </div>
        ) : (
            notebook.snippets.map((snippet) => (
            <CodeBlock key={snippet.id} snippet={snippet} />
            ))
        )}
      </div>

      {notebook.slug === 'shared' && (
          <div className="mt-12 p-4 bg-gray-50 border border-line text-center">
              <p className="text-sm text-pencil mb-2">This is a shared read-only view.</p>
              <Link to="/" className="text-ink font-bold hover:underline">Create your own notebook</Link>
          </div>
      )}
    </Layout>
  );
};